/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.tool;
import javax.swing.*;

/**
 *
 * @author Paul
 */
public class GraphicalUserInterface extends JFrame {

    /**
     * Creates new form GraphicalUserInterface
     */
    public GraphicalUserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_template = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        btn_category = new javax.swing.JButton();
        btn_question = new javax.swing.JButton();
        btn_quit = new javax.swing.JButton();
        pnl_content = new javax.swing.JPanel();
        pnl_start = new javax.swing.JPanel();
        pnl_categoryList = new javax.swing.JPanel();
        lbl_categoryHeadline = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("qTool");

        pnl_template.setBackground(new java.awt.Color(255, 255, 255));

        btn_start.setBackground(new java.awt.Color(255, 255, 255));
        btn_start.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_start.setText("Start");
        btn_start.setFocusable(false);
        btn_start.setMaximumSize(new java.awt.Dimension(120, 35));
        btn_start.setMinimumSize(new java.awt.Dimension(120, 35));
        btn_start.setPreferredSize(new java.awt.Dimension(120, 35));

        btn_category.setBackground(new java.awt.Color(255, 255, 255));
        btn_category.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_category.setText("Kategorien");
        btn_category.setFocusable(false);
        btn_category.setMaximumSize(new java.awt.Dimension(100, 35));
        btn_category.setMinimumSize(new java.awt.Dimension(100, 35));
        btn_category.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoryActionPerformed(evt);
            }
        });

        btn_question.setBackground(new java.awt.Color(255, 255, 255));
        btn_question.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_question.setText("Fragen");
        btn_question.setFocusable(false);
        btn_question.setMaximumSize(new java.awt.Dimension(100, 35));
        btn_question.setMinimumSize(new java.awt.Dimension(100, 35));
        btn_question.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_questionActionPerformed(evt);
            }
        });

        btn_quit.setBackground(new java.awt.Color(255, 255, 255));
        btn_quit.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_quit.setText("Beenden");
        btn_quit.setFocusable(false);
        btn_quit.setMaximumSize(new java.awt.Dimension(100, 35));
        btn_quit.setMinimumSize(new java.awt.Dimension(100, 35));
        btn_quit.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitActionPerformed(evt);
            }
        });

        pnl_content.setLayout(new java.awt.CardLayout());
        pnl_content.add(pnl_start, "card2");

        lbl_categoryHeadline.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        lbl_categoryHeadline.setText("Kategorien");

        javax.swing.GroupLayout pnl_categoryListLayout = new javax.swing.GroupLayout(pnl_categoryList);
        pnl_categoryList.setLayout(pnl_categoryListLayout);
        pnl_categoryListLayout.setHorizontalGroup(
            pnl_categoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_categoryListLayout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(lbl_categoryHeadline)
                .addContainerGap(386, Short.MAX_VALUE))
        );
        pnl_categoryListLayout.setVerticalGroup(
            pnl_categoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_categoryListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_categoryHeadline)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        pnl_content.add(pnl_categoryList, "card3");

        javax.swing.GroupLayout pnl_templateLayout = new javax.swing.GroupLayout(pnl_template);
        pnl_template.setLayout(pnl_templateLayout);
        pnl_templateLayout.setHorizontalGroup(
            pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_templateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_templateLayout.createSequentialGroup()
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_quit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_templateLayout.setVerticalGroup(
            pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_templateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_template, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_template, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoryActionPerformed
        
    }//GEN-LAST:event_btn_categoryActionPerformed

    private void btn_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_questionActionPerformed

    private void btn_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_quitActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_category;
    private javax.swing.JButton btn_question;
    private javax.swing.JButton btn_quit;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel lbl_categoryHeadline;
    private javax.swing.JPanel pnl_categoryList;
    private javax.swing.JPanel pnl_content;
    private javax.swing.JPanel pnl_start;
    private javax.swing.JPanel pnl_template;
    // End of variables declaration//GEN-END:variables
}
