/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.tool;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Paul
 */
public class GraphicalUserInterface extends JFrame {

    /**
     * Creates new form GraphicalUserInterface
     */
    public GraphicalUserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_template = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        btn_categories = new javax.swing.JButton();
        btn_questions = new javax.swing.JButton();
        btn_quit = new javax.swing.JButton();
        btn_options = new javax.swing.JButton();
        pnl_content = new javax.swing.JPanel();
        pnl_start = new javax.swing.JPanel();
        pnl_categoryList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        padding_top = new javax.swing.JPanel();
        padding_topLeft1 = new javax.swing.JPanel();
        lbl_headlineQuestions1 = new javax.swing.JLabel();
        padding_right = new javax.swing.JPanel();
        pnl_questionList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_questions = new javax.swing.JList();
        padding_top1 = new javax.swing.JPanel();
        padding_topLeft = new javax.swing.JPanel();
        lbl_headlineQuestions = new javax.swing.JLabel();
        padding_topRight = new javax.swing.JPanel();
        lbl_headlineAnswers = new javax.swing.JLabel();
        padding_right1 = new javax.swing.JPanel();
        pnl_answerList = new javax.swing.JPanel();
        pnl_aAnswer = new javax.swing.JPanel();
        lbl_aAnswer = new javax.swing.JLabel();
        pnl_bAnswer = new javax.swing.JPanel();
        lbl_bAnswer = new javax.swing.JLabel();
        pnl_cAnswer = new javax.swing.JPanel();
        lbl_cAnswer = new javax.swing.JLabel();
        pnl_dAnswer = new javax.swing.JPanel();
        lbl_dAnswer = new javax.swing.JLabel();
        btn_editAnswer = new javax.swing.JButton();
        btn_deleteAnswer = new javax.swing.JButton();
        btn_readyAnswer = new javax.swing.JButton();
        btn_editAnswer1 = new javax.swing.JButton();
        pnl_questionEdit = new javax.swing.JPanel();
        pnl_options = new javax.swing.JPanel();
        txt_dbHost = new javax.swing.JTextField();
        txt_dbPort = new javax.swing.JTextField();
        txt_dbName = new javax.swing.JTextField();
        txt_dbUser = new javax.swing.JTextField();
        btn_readyOptions = new javax.swing.JButton();
        lbl_headlineDatabaseConnecation = new javax.swing.JLabel();
        padding_left1 = new javax.swing.JPanel();
        padding_right2 = new javax.swing.JPanel();
        pwd_dbPassword = new javax.swing.JPasswordField();
        lbl_navigation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("qTool");

        pnl_template.setBackground(new java.awt.Color(255, 255, 255));

        btn_start.setBackground(new java.awt.Color(102, 204, 255));
        btn_start.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_start.setText("Start");
        btn_start.setFocusable(false);
        btn_start.setMaximumSize(new java.awt.Dimension(120, 35));
        btn_start.setMinimumSize(new java.awt.Dimension(120, 35));
        btn_start.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        btn_categories.setBackground(new java.awt.Color(255, 255, 255));
        btn_categories.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_categories.setText("Kategorien");
        btn_categories.setFocusable(false);
        btn_categories.setMaximumSize(new java.awt.Dimension(100, 35));
        btn_categories.setMinimumSize(new java.awt.Dimension(100, 35));
        btn_categories.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoriesActionPerformed(evt);
            }
        });

        btn_questions.setBackground(new java.awt.Color(255, 255, 255));
        btn_questions.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_questions.setText("Fragen");
        btn_questions.setFocusable(false);
        btn_questions.setMaximumSize(new java.awt.Dimension(100, 35));
        btn_questions.setMinimumSize(new java.awt.Dimension(100, 35));
        btn_questions.setPreferredSize(new java.awt.Dimension(120, 35));
        btn_questions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_questionsActionPerformed(evt);
            }
        });

        btn_quit.setBackground(new java.awt.Color(255, 255, 255));
        btn_quit.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_quit.setText("Beenden");
        btn_quit.setFocusable(false);
        btn_quit.setMaximumSize(new java.awt.Dimension(120, 35));
        btn_quit.setMinimumSize(new java.awt.Dimension(120, 35));
        btn_quit.setPreferredSize(new java.awt.Dimension(130, 35));
        btn_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitActionPerformed(evt);
            }
        });

        btn_options.setBackground(new java.awt.Color(255, 255, 255));
        btn_options.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_options.setText("Einstellungen");
        btn_options.setFocusable(false);
        btn_options.setMaximumSize(new java.awt.Dimension(120, 35));
        btn_options.setMinimumSize(new java.awt.Dimension(120, 35));
        btn_options.setPreferredSize(new java.awt.Dimension(130, 35));
        btn_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_optionsActionPerformed(evt);
            }
        });

        pnl_content.setLayout(new java.awt.CardLayout());

        pnl_start.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_startLayout = new javax.swing.GroupLayout(pnl_start);
        pnl_start.setLayout(pnl_startLayout);
        pnl_startLayout.setHorizontalGroup(
            pnl_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        pnl_startLayout.setVerticalGroup(
            pnl_startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        pnl_content.add(pnl_start, "card2");

        pnl_categoryList.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        padding_top.setBackground(new java.awt.Color(255, 255, 255));

        padding_topLeft1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_headlineQuestions1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbl_headlineQuestions1.setText("Kategorien");

        javax.swing.GroupLayout padding_topLeft1Layout = new javax.swing.GroupLayout(padding_topLeft1);
        padding_topLeft1.setLayout(padding_topLeft1Layout);
        padding_topLeft1Layout.setHorizontalGroup(
            padding_topLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padding_topLeft1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(lbl_headlineQuestions1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        padding_topLeft1Layout.setVerticalGroup(
            padding_topLeft1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, padding_topLeft1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lbl_headlineQuestions1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout padding_topLayout = new javax.swing.GroupLayout(padding_top);
        padding_top.setLayout(padding_topLayout);
        padding_topLayout.setHorizontalGroup(
            padding_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(padding_topLeft1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        padding_topLayout.setVerticalGroup(
            padding_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, padding_topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(padding_topLeft1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        padding_right.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout padding_rightLayout = new javax.swing.GroupLayout(padding_right);
        padding_right.setLayout(padding_rightLayout);
        padding_rightLayout.setHorizontalGroup(
            padding_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );
        padding_rightLayout.setVerticalGroup(
            padding_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_categoryListLayout = new javax.swing.GroupLayout(pnl_categoryList);
        pnl_categoryList.setLayout(pnl_categoryListLayout);
        pnl_categoryListLayout.setHorizontalGroup(
            pnl_categoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_categoryListLayout.createSequentialGroup()
                .addGroup(pnl_categoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_categoryListLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(padding_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(padding_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnl_categoryListLayout.setVerticalGroup(
            pnl_categoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_categoryListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(padding_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_categoryListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(padding_right, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pnl_content.add(pnl_categoryList, "card3");

        pnl_questionList.setBackground(new java.awt.Color(255, 255, 255));

        lst_questions.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lst_questions.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lst_questions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lst_questions);

        padding_top1.setBackground(new java.awt.Color(255, 255, 255));
        padding_top1.setPreferredSize(new java.awt.Dimension(100, 100));

        padding_topLeft.setBackground(new java.awt.Color(255, 255, 255));

        lbl_headlineQuestions.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbl_headlineQuestions.setText("Fragen");

        javax.swing.GroupLayout padding_topLeftLayout = new javax.swing.GroupLayout(padding_topLeft);
        padding_topLeft.setLayout(padding_topLeftLayout);
        padding_topLeftLayout.setHorizontalGroup(
            padding_topLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padding_topLeftLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(lbl_headlineQuestions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        padding_topLeftLayout.setVerticalGroup(
            padding_topLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, padding_topLeftLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(lbl_headlineQuestions)
                .addGap(29, 29, 29))
        );

        padding_topRight.setBackground(new java.awt.Color(255, 255, 255));

        lbl_headlineAnswers.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbl_headlineAnswers.setText("Antworten");

        javax.swing.GroupLayout padding_topRightLayout = new javax.swing.GroupLayout(padding_topRight);
        padding_topRight.setLayout(padding_topRightLayout);
        padding_topRightLayout.setHorizontalGroup(
            padding_topRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padding_topRightLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(lbl_headlineAnswers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        padding_topRightLayout.setVerticalGroup(
            padding_topRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, padding_topRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_headlineAnswers)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout padding_top1Layout = new javax.swing.GroupLayout(padding_top1);
        padding_top1.setLayout(padding_top1Layout);
        padding_top1Layout.setHorizontalGroup(
            padding_top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padding_top1Layout.createSequentialGroup()
                .addComponent(padding_topLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(padding_topRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        padding_top1Layout.setVerticalGroup(
            padding_top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padding_top1Layout.createSequentialGroup()
                .addGroup(padding_top1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(padding_topLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(padding_topRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        padding_right1.setBackground(new java.awt.Color(255, 255, 255));

        pnl_answerList.setBackground(new java.awt.Color(255, 255, 255));

        pnl_aAnswer.setBackground(new java.awt.Color(153, 255, 153));
        pnl_aAnswer.setPreferredSize(new java.awt.Dimension(100, 78));

        lbl_aAnswer.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnl_aAnswerLayout = new javax.swing.GroupLayout(pnl_aAnswer);
        pnl_aAnswer.setLayout(pnl_aAnswerLayout);
        pnl_aAnswerLayout.setHorizontalGroup(
            pnl_aAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_aAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_aAnswerLayout.setVerticalGroup(
            pnl_aAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_aAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_aAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_bAnswer.setBackground(new java.awt.Color(255, 102, 102));
        pnl_bAnswer.setPreferredSize(new java.awt.Dimension(100, 78));

        lbl_bAnswer.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnl_bAnswerLayout = new javax.swing.GroupLayout(pnl_bAnswer);
        pnl_bAnswer.setLayout(pnl_bAnswerLayout);
        pnl_bAnswerLayout.setHorizontalGroup(
            pnl_bAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_bAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_bAnswerLayout.setVerticalGroup(
            pnl_bAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_bAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_bAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_cAnswer.setBackground(new java.awt.Color(255, 102, 102));
        pnl_cAnswer.setPreferredSize(new java.awt.Dimension(100, 78));

        lbl_cAnswer.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnl_cAnswerLayout = new javax.swing.GroupLayout(pnl_cAnswer);
        pnl_cAnswer.setLayout(pnl_cAnswerLayout);
        pnl_cAnswerLayout.setHorizontalGroup(
            pnl_cAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_cAnswerLayout.setVerticalGroup(
            pnl_cAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_dAnswer.setBackground(new java.awt.Color(255, 102, 102));
        pnl_dAnswer.setPreferredSize(new java.awt.Dimension(100, 78));

        lbl_dAnswer.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnl_dAnswerLayout = new javax.swing.GroupLayout(pnl_dAnswer);
        pnl_dAnswer.setLayout(pnl_dAnswerLayout);
        pnl_dAnswerLayout.setHorizontalGroup(
            pnl_dAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_dAnswerLayout.setVerticalGroup(
            pnl_dAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_dAnswerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_answerListLayout = new javax.swing.GroupLayout(pnl_answerList);
        pnl_answerList.setLayout(pnl_answerListLayout);
        pnl_answerListLayout.setHorizontalGroup(
            pnl_answerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_aAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(pnl_bAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(pnl_cAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(pnl_dAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        pnl_answerListLayout.setVerticalGroup(
            pnl_answerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_answerListLayout.createSequentialGroup()
                .addComponent(pnl_aAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_bAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_cAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_dAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_editAnswer.setBackground(new java.awt.Color(255, 255, 255));
        btn_editAnswer.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_editAnswer.setText("Bearbeiten");
        btn_editAnswer.setFocusable(false);

        btn_deleteAnswer.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteAnswer.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_deleteAnswer.setText("Löschen");
        btn_deleteAnswer.setFocusable(false);
        btn_deleteAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteAnswerActionPerformed(evt);
            }
        });

        btn_readyAnswer.setBackground(new java.awt.Color(255, 255, 255));
        btn_readyAnswer.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_readyAnswer.setText("Fertig");
        btn_readyAnswer.setFocusable(false);
        btn_readyAnswer.setPreferredSize(new java.awt.Dimension(73, 39));
        btn_readyAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readyAnswerActionPerformed(evt);
            }
        });

        btn_editAnswer1.setBackground(new java.awt.Color(255, 255, 255));
        btn_editAnswer1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_editAnswer1.setText("Neu");
        btn_editAnswer1.setFocusable(false);

        javax.swing.GroupLayout padding_right1Layout = new javax.swing.GroupLayout(padding_right1);
        padding_right1.setLayout(padding_right1Layout);
        padding_right1Layout.setHorizontalGroup(
            padding_right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padding_right1Layout.createSequentialGroup()
                .addComponent(btn_editAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btn_readyAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnl_answerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        padding_right1Layout.setVerticalGroup(
            padding_right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(padding_right1Layout.createSequentialGroup()
                .addComponent(pnl_answerList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(padding_right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_readyAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnl_questionListLayout = new javax.swing.GroupLayout(pnl_questionList);
        pnl_questionList.setLayout(pnl_questionListLayout);
        pnl_questionListLayout.setHorizontalGroup(
            pnl_questionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_questionListLayout.createSequentialGroup()
                .addComponent(padding_top1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnl_questionListLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(padding_right1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_questionListLayout.setVerticalGroup(
            pnl_questionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_questionListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(padding_top1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_questionListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(padding_right1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_content.add(pnl_questionList, "card4");

        javax.swing.GroupLayout pnl_questionEditLayout = new javax.swing.GroupLayout(pnl_questionEdit);
        pnl_questionEdit.setLayout(pnl_questionEditLayout);
        pnl_questionEditLayout.setHorizontalGroup(
            pnl_questionEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        pnl_questionEditLayout.setVerticalGroup(
            pnl_questionEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        pnl_content.add(pnl_questionEdit, "card7");

        pnl_options.setBackground(new java.awt.Color(255, 255, 255));

        txt_dbHost.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_dbHost.setForeground(new java.awt.Color(204, 204, 204));
        txt_dbHost.setText("Host");
        txt_dbHost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dbHostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_dbHostFocusLost(evt);
            }
        });

        txt_dbPort.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_dbPort.setForeground(new java.awt.Color(204, 204, 204));
        txt_dbPort.setText("Port");
        txt_dbPort.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dbPortFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_dbPortFocusLost(evt);
            }
        });

        txt_dbName.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_dbName.setForeground(new java.awt.Color(204, 204, 204));
        txt_dbName.setText("Name der Datenbank");
        txt_dbName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dbNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_dbNameFocusLost(evt);
            }
        });

        txt_dbUser.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txt_dbUser.setForeground(new java.awt.Color(204, 204, 204));
        txt_dbUser.setText("Benutzer");
        txt_dbUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dbUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_dbUserFocusLost(evt);
            }
        });

        btn_readyOptions.setBackground(new java.awt.Color(255, 255, 255));
        btn_readyOptions.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        btn_readyOptions.setText("Fertig");
        btn_readyOptions.setFocusable(false);
        btn_readyOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_readyOptionsActionPerformed(evt);
            }
        });

        lbl_headlineDatabaseConnecation.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        lbl_headlineDatabaseConnecation.setText("Datenbank-Verbindung");

        padding_left1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout padding_left1Layout = new javax.swing.GroupLayout(padding_left1);
        padding_left1.setLayout(padding_left1Layout);
        padding_left1Layout.setHorizontalGroup(
            padding_left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        padding_left1Layout.setVerticalGroup(
            padding_left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        padding_right2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout padding_right2Layout = new javax.swing.GroupLayout(padding_right2);
        padding_right2.setLayout(padding_right2Layout);
        padding_right2Layout.setHorizontalGroup(
            padding_right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        padding_right2Layout.setVerticalGroup(
            padding_right2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pwd_dbPassword.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        pwd_dbPassword.setForeground(new java.awt.Color(204, 204, 204));
        pwd_dbPassword.setText("Passwort");
        pwd_dbPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwd_dbPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwd_dbPasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnl_optionsLayout = new javax.swing.GroupLayout(pnl_options);
        pnl_options.setLayout(pnl_optionsLayout);
        pnl_optionsLayout.setHorizontalGroup(
            pnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_optionsLayout.createSequentialGroup()
                .addComponent(padding_left1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_headlineDatabaseConnecation)
                    .addComponent(txt_dbHost)
                    .addComponent(txt_dbPort)
                    .addComponent(txt_dbName, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(txt_dbUser)
                    .addComponent(btn_readyOptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_dbPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(padding_right2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_optionsLayout.setVerticalGroup(
            pnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_optionsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbl_headlineDatabaseConnecation)
                        .addGap(36, 36, 36)
                        .addComponent(txt_dbHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_dbPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_dbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_dbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwd_dbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_readyOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(138, Short.MAX_VALUE))
                    .addComponent(padding_left1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(padding_right2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnl_content.add(pnl_options, "card5");

        lbl_navigation.setFont(new java.awt.Font("Calibri Light", 0, 26)); // NOI18N
        lbl_navigation.setForeground(new java.awt.Color(51, 153, 255));
        lbl_navigation.setText("Übersicht");

        javax.swing.GroupLayout pnl_templateLayout = new javax.swing.GroupLayout(pnl_template);
        pnl_template.setLayout(pnl_templateLayout);
        pnl_templateLayout.setHorizontalGroup(
            pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_templateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_templateLayout.createSequentialGroup()
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_questions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_navigation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_options, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_quit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_templateLayout.setVerticalGroup(
            pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_templateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_templateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_questions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_quit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_navigation, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_template, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_template, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setActive(javax.swing.JButton btn){
        btn.setBackground(new java.awt.Color(102,204,255));
    }
    
    public void setInActiveAllButtons(){
        btn_start.setBackground(new java.awt.Color(255,255,255));
        btn_categories.setBackground(new java.awt.Color(255,255,255));
        btn_questions.setBackground(new java.awt.Color(255,255,255));
        btn_options.setBackground(new java.awt.Color(255,255,255));
        btn_quit.setBackground(new java.awt.Color(255,255,255));
    }
    
    private void btn_categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoriesActionPerformed
        CardLayout cl = (CardLayout) (pnl_content.getLayout());
        cl.first(pnl_content);
        cl.next(pnl_content);
        lbl_navigation.setText("Kategorien");
        setInActiveAllButtons();
        setActive(btn_categories);
    }//GEN-LAST:event_btn_categoriesActionPerformed

    private void btn_questionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_questionsActionPerformed
        CardLayout cl = (CardLayout) (pnl_content.getLayout());
        cl.first(pnl_content);
        cl.next(pnl_content);
        cl.next(pnl_content);
        lbl_navigation.setText("Fragen");
        setInActiveAllButtons();
        setActive(btn_questions);
    }//GEN-LAST:event_btn_questionsActionPerformed

    private void btn_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_quitActionPerformed

    private void btn_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_optionsActionPerformed
        CardLayout cl = (CardLayout) (pnl_content.getLayout());
        cl.first(pnl_content);
        cl.next(pnl_content);
        cl.next(pnl_content);
        cl.next(pnl_content);
        lbl_navigation.setText("Einstellungen");
        setInActiveAllButtons();
        setActive(btn_options);
    }//GEN-LAST:event_btn_optionsActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        CardLayout cl = (CardLayout) (pnl_content.getLayout());
        cl.first(pnl_content);
        lbl_navigation.setText("Übersicht");
        setInActiveAllButtons();
        setActive(btn_start);
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_readyAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readyAnswerActionPerformed

    }//GEN-LAST:event_btn_readyAnswerActionPerformed

    private void txt_dbHostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dbHostFocusGained
        if (txt_dbHost.getText().equals("Host")){
            txt_dbHost.setText(null);
            txt_dbHost.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_dbHostFocusGained

    private void txt_dbPortFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dbPortFocusGained
        if (txt_dbPort.getText().equals("Port")){
            txt_dbPort.setText(null);
            txt_dbPort.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_dbPortFocusGained

    private void txt_dbHostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dbHostFocusLost
        if(txt_dbHost.getText().equals("")){
            txt_dbHost.setForeground(new java.awt.Color(204,204,204));
            txt_dbHost.setText("Host");
        }
    }//GEN-LAST:event_txt_dbHostFocusLost

    private void txt_dbPortFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dbPortFocusLost
        if(txt_dbPort.getText().equals("")){
            txt_dbPort.setForeground(new java.awt.Color(204,204,204));
            txt_dbPort.setText("Port");
        }
    }//GEN-LAST:event_txt_dbPortFocusLost

    private void txt_dbNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dbNameFocusGained
        if (txt_dbName.getText().equals("Name der Datenbank")){
            txt_dbName.setText(null);
            txt_dbName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_dbNameFocusGained

    private void txt_dbNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dbNameFocusLost
        if(txt_dbName.getText().equals("")){
            txt_dbName.setForeground(new java.awt.Color(204,204,204));
            txt_dbName.setText("Name der Datenbank");
        }
    }//GEN-LAST:event_txt_dbNameFocusLost

    private void txt_dbUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dbUserFocusGained
        if (txt_dbUser.getText().equals("Benutzer")){
            txt_dbUser.setText(null);
            txt_dbUser.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_dbUserFocusGained

    private void txt_dbUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dbUserFocusLost
        if(txt_dbUser.getText().equals("")){
            txt_dbUser.setForeground(new java.awt.Color(204,204,204));
            txt_dbUser.setText("Benutzer");
        }
    }//GEN-LAST:event_txt_dbUserFocusLost

    private void btn_readyOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_readyOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_readyOptionsActionPerformed

    private void pwd_dbPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwd_dbPasswordFocusGained
        pwd_dbPassword.setText(null);
        pwd_dbPassword.setForeground(Color.black);
    }//GEN-LAST:event_pwd_dbPasswordFocusGained

    private void pwd_dbPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwd_dbPasswordFocusLost

    }//GEN-LAST:event_pwd_dbPasswordFocusLost

    private void btn_deleteAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteAnswerActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_categories;
    private javax.swing.JButton btn_deleteAnswer;
    private javax.swing.JButton btn_editAnswer;
    private javax.swing.JButton btn_editAnswer1;
    private javax.swing.JButton btn_options;
    private javax.swing.JButton btn_questions;
    private javax.swing.JButton btn_quit;
    private javax.swing.JButton btn_readyAnswer;
    private javax.swing.JButton btn_readyOptions;
    private javax.swing.JButton btn_start;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_aAnswer;
    private javax.swing.JLabel lbl_bAnswer;
    private javax.swing.JLabel lbl_cAnswer;
    private javax.swing.JLabel lbl_dAnswer;
    private javax.swing.JLabel lbl_headlineAnswers;
    private javax.swing.JLabel lbl_headlineDatabaseConnecation;
    private javax.swing.JLabel lbl_headlineQuestions;
    private javax.swing.JLabel lbl_headlineQuestions1;
    private javax.swing.JLabel lbl_navigation;
    private javax.swing.JList lst_questions;
    private javax.swing.JPanel padding_left1;
    private javax.swing.JPanel padding_right;
    private javax.swing.JPanel padding_right1;
    private javax.swing.JPanel padding_right2;
    private javax.swing.JPanel padding_top;
    private javax.swing.JPanel padding_top1;
    private javax.swing.JPanel padding_topLeft;
    private javax.swing.JPanel padding_topLeft1;
    private javax.swing.JPanel padding_topRight;
    private javax.swing.JPanel pnl_aAnswer;
    private javax.swing.JPanel pnl_answerList;
    private javax.swing.JPanel pnl_bAnswer;
    private javax.swing.JPanel pnl_cAnswer;
    private javax.swing.JPanel pnl_categoryList;
    private javax.swing.JPanel pnl_content;
    private javax.swing.JPanel pnl_dAnswer;
    private javax.swing.JPanel pnl_options;
    private javax.swing.JPanel pnl_questionEdit;
    private javax.swing.JPanel pnl_questionList;
    private javax.swing.JPanel pnl_start;
    private javax.swing.JPanel pnl_template;
    private javax.swing.JPasswordField pwd_dbPassword;
    private javax.swing.JTextField txt_dbHost;
    private javax.swing.JTextField txt_dbName;
    private javax.swing.JTextField txt_dbPort;
    private javax.swing.JTextField txt_dbUser;
    // End of variables declaration//GEN-END:variables
}
